name: envgen
description: "A tool to generate flavor environment variable files for Flutter projects using envied."
version: 0.1.1
homepage: https://github.com/arkariz/envgen
repository: https://github.com/arkariz/envgen

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  args: ^2.7.0
  path: ^1.9.1

dev_dependencies:
  melos: ^7.5.1
  flutter_lints: ^6.0.0

melos:
  repository: https://github.com/arkariz/envgen
  useRootAsPackage: true
  command:
    version:
      branch: main
      includeCommitId: true
      includeDate: true
